### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by masa-2a**
fixed spelling errors

### CODE REVIEW

**Comment by StevenQiaoUT** [comment]
Fixed spelling mistake.

**Comment by PuravG** [comment]
OMGGG THANK YOU FOR FIXING THIS. our very own grammarly premium subscriber!

PS. Imma merge it now.

**Review by PuravG — COMMENTED** [review]
OMGGG THANK YOU FOR FIXING THIS. our very own grammarly premium subscriber!

PS. Imma merge it now.

**Review by PuravG — APPROVED** [review]
OMGGG THANK YOU FOR FIXING THIS. our very own grammarly premium subscriber!

PS. Imma merge it now.

**Review by StevenQiaoUT — COMMENTED** [review]
Excellent work and great endeavors in achieving spelling correctness

**Comment by masa-2a** [comment]
thanks guys

**Pull request merged**
